//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class STDersTakip
    {
        public int Id { get; set; }
        public int Ogrenci { get; set; }
        public int Ders { get; set; }
        public Nullable<System.DateTime> DersTarihi { get; set; }
    
        public virtual STDer STDer { get; set; }
        public virtual STOgrenci STOgrenci { get; set; }
    }
}
