//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp_FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class workStationReservations
    {
        public int id { get; set; }
        public int officeId { get; set; }
        public int workStationId { get; set; }
        public int personnelId { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
    
        public virtual offices offices { get; set; }
        public virtual personnels personnels { get; set; }
        public virtual workStations workStations { get; set; }
    }
}
